[package]
name = "irc"
version = "0.12.3"
description = "A simple, thread-safe, and async-friendly IRC client library."
authors = ["Aaron Weiss <awe@pdgn.co>"]
license = "MPL-2.0"
keywords = ["irc", "client", "thread-safe", "async", "tokio"]
categories = ["asynchronous", "network-programming"]
documentation = "https://docs.rs/irc/"
repository = "https://github.com/aatxe/irc"
readme = "README.md"

[features]
default = ["ctcp", "json"]
ctcp = []
nochanlists = []
json = ["serde_json"]
yaml = ["serde_yaml"]

[dependencies]
bufstream = "0.1"
bytes = "0.4"
chrono = "0.4"
encoding = "0.2"
error-chain = "0.10"
futures = "0.1"
native-tls = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", optional = true }
serde_yaml = { version = "0.7", optional = true }
tokio-core = "0.1"
tokio-io = "0.1"
tokio-mockstream = "1.1"
tokio-timer = "0.1"
tokio-tls = "0.1"
toml = { version = "0.4", optional = true }

[dev-dependencies]
args = "2.0"
getopts = "0.2"
